pipeline {
    agent any

    tools{
        maven 'Maven'//Jenkins Tools에 설정한 메이븐의 이름
    }

    environment{
        JAVA_HOME = 'C:\\dev\\java-11-openjdk-11.0.15.9-1'//자바가 설치된 경로
        PATH = "${env.JAVA_HOME}\\bin;${env.PATH}"
    }

    //trigger{
    //    pollSCM('H/6***1-5')
    //}

    stages {
        stage('clone repository') {
            steps {
                git branch:'main',credentialsId:'github-token',url:'https://github.com/choiyeon/test_jenkins2.git'
            }
        }
        stage('build WAR'){
            steps{
                script{
                    def mvnHome = tool name:'Maven', type:'hudson.tasks.Maven$MavenInstallation'
                    withEnv(["MAVEN_HOME=${mvnHome}"]){
                        //pom.xml에 version노드의 이름으로 war가 target 디렉토리에 생성된다.
                        bat "\"${mvnHome}\\bin\\mvn\" clean package -DskipTests"
                    } 
                }
            }
        }
    }

}